story/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_1.urls')),
    path('', include('story_4.urls')),
    path('subject/', include('story_5.urls')),
    path('activity/', include('story_6.urls')),
]

story_1/urls.py
from django.urls import path
from . import views

app_name = 'story_1'

urlpatterns = [
    path('story-1', views.home, name='home'),
]

story_4/urls.py
from django.urls import path
from . import views

app_name = 'story_4'

urlpatterns = [
    path('', views.home, name='home'),
    path('extra/', views.extra, name='extra'),
    path('time/', views.time, name='time'),
    path('time/<str:index>/', views.time, name='time'),
]

story_5/urls.py
from django.urls import path
from . import views

app_name = 'story_5'

urlpatterns = [
    path('', views.subject, name='subject'),
    path('detail/<int:index>/', views.subject_detail, name='subject_detail'),
    path('add/', views.add_subject, name='add_subject'),
]

story_6/urls.py
from django.urls import path
from . import views

app_name = 'story_6'

urlpatterns = [
    path('', views.activity, name='activity'),
    path('add/', views.add_activity, name='add_activity'),
    path('register/<int:index>/', views.register, name='register'),
]

story_1/models.py
from django.db import models

# Create your models here.

story_4/models.py
from django.db import models

# Create your models here.

story_5/models.py
from django.db import models

# Create your models here.
class Subject(models.Model):
	matkul = models.CharField('Subject', max_length=120, null=True)
	dosen = models.CharField('Lecturer', max_length=120, null=True)
	sks = models.IntegerField('Credit(s)', null=True)
	deskripsi = models.TextField('Description', blank=True)
	semester = models.CharField('Term', max_length=120, null=True, help_text='example : Odd 2019/2020')
	kelas = models.CharField('Classroom', max_length=120, null=True)

	def __str__(self):
		return self.matkul

class Task(models.Model):
	matkul = models.ForeignKey('Subject', on_delete=models.CASCADE, null=True)
	tugas = models.CharField('Task', max_length=120, null=True)
	deadline = models.DateField('Deadline', max_length=120, null=True)

	class Meta:
		ordering = ['deadline']

story_6/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
	kegiatan = models.CharField('Activity Name', max_length=120)
	
class Person(models.Model):
	kegiatan = models.ForeignKey('Activity', on_delete=models.CASCADE, null=True, blank=True)
	nama = models.CharField('Name', max_length=120)

story_5/forms.py
from django.forms import ModelForm
from .models import Subject

class SubjectForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Subject
		fields = '__all__'

story_6/forms.py
from django.forms import ModelForm
from .models import Activity, Person

class ActivityForm(ModelForm):
	required_css_class = 'required'
	class Meta:
		model = Activity
		fields = '__all__'

class PersonForm(ModelForm):
	class Meta:
		model = Person
		fields = ['nama']

story_1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

story_4/views.py
from django.shortcuts import render
from django.utils.timezone import utc
import datetime

# Create your views here.
def home(request):
    return render(request, 'homepage.html')

def extra(request):
    return render(request, 'extra_page.html')

def time(request, index="0"):
	time_zone = (7 + int(index)) % 24
	utc_time = datetime.datetime.utcnow().replace(tzinfo=utc)
	timezone_time = datetime.datetime.utcnow() + datetime.timedelta(hours=time_zone)

	context= {
	    'timezone_time': timezone_time,
	    'utc_time': utc_time,
	    'utc': time_zone,
    }
	return render(request, 'time.html', context)

story_5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Subject, Task
from .forms import SubjectForm
import datetime

# Create your views here.
def subject(request):
	if request.method == "POST":
		Subject.objects.get(id=request.POST['id']).delete()
		return redirect('/subject/')
	list_subject = Subject.objects.all()
	return render(request, 'subject_list.html', {'subject_list': list_subject})

def subject_detail(request, index):
	subject = Subject.objects.get(pk=index)
	task_list = Task.objects.filter(matkul_id=subject)

	overdue = task_list.filter(deadline__lt=datetime.date.today())
	near = task_list.filter(deadline__range=(datetime.date.today(), datetime.date.today() + datetime.timedelta(days=6)))
	far = task_list.filter(deadline__gte=datetime.date.today() + datetime.timedelta(days=7))

	context = {
		'subject' : subject,
		'overdue': overdue,
		'near' : near,
		'far' : far,
	}
	return render(request, 'subject_detail.html', context)

def add_subject(request):
	submitted = False
	if request.method == 'POST':
		form = SubjectForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect('/subject/add/?submitted=True')
	else:
		form = SubjectForm()
		if 'submitted' in request.GET:
			submitted = True
	return render(request, 'add_subject.html', {'form': form, 'submitted': submitted})

story_6/views.py
from django.shortcuts import render, redirect
from .models import Activity, Person
from .forms import ActivityForm, PersonForm

# Create your views here.
def activity(request):
	activity = Activity.objects.all()
	attendees = Person.objects.all()

	if request.method == "POST":
		Person.objects.get(id=request.POST['id']).delete()
		return redirect('/activity/')

	return render(request, 'activity.html', {'activity': activity, 'attendees': attendees})

def add_activity(request):
	if request.method == 'POST':
		form = ActivityForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/activity/')
	else:
		form = ActivityForm()
	return render(request, 'add_activity.html', {'form': form})

def register(request, index):
	if request.method == 'POST':
		form = PersonForm(request.POST)
		if form.is_valid():
			newPerson = Person(kegiatan=Activity.objects.get(id=index), nama=form.data['nama'])
			newPerson.save()
			return redirect('/activity/')
	else:
		form = PersonForm()
	return render(request, 'register.html', {'form': form})

story_1/templates/home.html
<html>
   {% load static %}
   <head>
      <title>Profil Diri</title>
   </head>
   <body>
      <h1 align="center"> Profil Diri </h1>
      <br/>
      
      <img src="{% static 'images/foto.jpg' %}" alt="foto diri" style=width:300px;height:300px/> 

      <p> <b> Nama</b> : Fairuza Raryasdya Ayunda </p>
      <p> <b> NPM</b> : 1906285610 </p>
      <p> <b> Angkatan</b> : 2019 </p>
      <p> <b> Tempat Kuliah</b> : Fakultas Ilmu Komputer, Universitas Indonesia</p>
      <p> <b> Hobi</b> : Main laptop </p>
      <p> <b> Deskripsi Diri</b> : </p>
      <p> Aku orang beruntung yang sepanjang hidupnya selalu diiringi doa kuat dari orang tua. Walaupun sedang menjalani jadwal perkuliahan yang padat di jurusan Ilmu Komputer, jam tidurku masih terhitung banyak. Selain itu, melihat anak kecil tertawa bahagia udah cukup membuatku senang. </p>
      

      <p> <b>Riwayat Pendidikan </b> : </p>
      <table border='1'>
         <tr align="center">
            <th> <b> Tahun </b> </th>
            <th> <b> Nama Sekolah </b> </th>
         
         <tr>
            <td align="center"> 2019 - Sekarang </td>
            <td> Universitas Indonesia </td> 
         </tr>
         
         <tr>
            <td align="center"> 2016 - 2019 </td>
            <td> SMAN 2 Kota Tangerang Selatan </td>
         </tr>
         </tr>
         
         <tr>
            <td align="center"> 2013 - 2016 </td>
            <td> SMP Islam Al-Azhar BSD </td>
         </tr>
         
         <tr>
            <td align="center"> 2007 - 2013 </td>
            <td> SD Islam Cikal Harapan I BSD </td>
         </tr>
         
         <tr>
            <td align="center"> 2003 - 2007 </td>
            <td> Taman Bermain Insan Kamil </td>
         </tr>
      </table>

      <br/>
      <p> <b> Media Sosial </b> : </p>
      <a href="https://instagram.com/fairuzafe" target="_blank">
         <img src="{% static 'images/instagram.png' %}" alt="instagram" style=width:50px;height:50px/> 
      </a>
      <a href="https://linkedin.com/in/raryasdya" target="_blank">
         <img src="{% static 'images/linkedin.png' %}" alt="linkedin" style=width:50px;height:50px/> 
      </a>
   </body>
</html>

story_4/templates/extra_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Extra Page {% endblock %}

{% block content %}
{% include 'navbar.html' %}

	<section id="section-a" class="container-fluid d-flex flex-wrap">
		<p class="quote align-self-end">
			“Life’s most persistent and urgent question is : ‘What are you doing for others?’ “ <br/>
			- Marthin Luther King Jr.
		</p>
	</section>

	<section id="section-b" class="container-fluid d-flex flex-wrap align-content-center">
		<div class="row justify-content-center">
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/sospro-1.jpg' %}" alt="sospro-1">
		  </div>
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/sospro-2.jpg' %}" alt="sospro-2">
		  </div>
		</div>
		<br>
		<div class="heading-1 col-12">
			SOCIAL PROJECT
		</div>
		<div class="heading-2 col-12">
			23rd October 2019
		</div>
		<br>
		<div class="paragraph col-12">
			This event was held by the freshmen of Fasilkom UI as a part of our Student Orientation. I was one of the mentor who taught high-schoolers in Sekolah Master, Depok. It was both thrilling and fun since we are almost the same age.
		</div>
	</section>

	<section id="section-c" class="container-fluid d-flex flex-wrap align-content-center">
		<div class="row justify-content-center">
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/sikola-1.jpg' %}" alt="sikola-1">
		  </div>
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/sikola-2.jpg' %}" alt="sikola-2">
		  </div>
		</div>
		<br>
		<div class="heading-1 col-12">
			SIKOLA
		</div>
		<div class="heading-2 col-12">
			7th December 2019
		</div>
		<br>
		<div class="paragraph col-12">
			SIKOLA is the closing event of Pedas, an annual donation program for Fasilkom’s staff. I was chosen to host the event with Akbar. We played games, ate lunch together, and at the end of the event, we also donated school stationery.
		</div>
	</section>

	<section id="section-d" class="container-fluid d-flex flex-wrap align-content-center">
		<div class="row justify-content-center">
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/bebenah-1.jpg' %}" alt="bebenah-1">
		  </div>
		  <div class="col-12 col-sm-5">
			<img class="image" src="{% static 'images/bebenah-2.jpg' %}" alt="bebenah-2">
		  </div>
		</div>
		<br>
		<div class="heading-1 col-12">
			BEBENAH BANTEN
		</div>
		<div class="heading-2 col-12">
			19th - 23rd January 2020
		</div>
		<br>
		<div class="paragraph col-12">
			Bebenah Banten is an annual community development event held by FORKOMA UI. I was assigned to teach 2nd grade students of SDN 1 Nayagati for 2 days. We taught them clean and healthy lifestyle and balanced diet. Besides, we also held a free medical check-up at Kampung Cakuem, Desa Nayagati.
		</div>
	</section>

	<section id="section-e" class="container-fluid">
		<div class="row">
			<div class="col-sm-6 left-side">
				<button type="button" class="btn align-self-center" data-toggle="modal" data-target="#exampleModal">
					<span class="iconify" data-inline="false" data-icon="ant-design:picture-outlined" style="font-size: 290px;"></span>
        		</button>
	  			and hopefully there will be more to come :) </br>
	  			(ps. you can click the gallery icon to see more photos)
		  	</div>

		  	<div class="col-sm-6 right-side">
				<a href="{% url 'story_4:home' %}">
				  <div class="d-flex click-2 m-auto">
	  				BACK TO HOME
	  			  </div>
	  			</a>
		  	</div>
  		</div>
  	</section>

  	<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="section-title" id="exampleModalLabel" style="padding:0px;"> My Gallery </h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <img class="d-block w-100" src="{% static 'images/so-1.jpg' %}" alt="First slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/so-2.jpg' %}" alt="Second slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/si-1.jpg' %}" alt="Third slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/si-2.jpg' %}" alt="Fourth slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/be-1.jpg' %}" alt="Fifth slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/be-2.jpg' %}" alt="Sixth slide">
                            </div>

                            <div class="carousel-item">
                                <img class="d-block w-100" src="{% static 'images/be-3.jpg' %}" alt="Seventh slide">
                            </div>
                        </div>

                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>

                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

story_4/templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Fairuza Raryasdya {% endblock %}

{% block content %}
{% include 'navbar.html' %}

	<section id="home" class="container-fluid">
		<h1 class="title"> WELCOME! </h1>
		<p class="subtitle"> My name is Fairuza, and now you're at my website</p>
		<a href="#about">
			<img src="{% static 'images/Arrow.png' %}" alt="Arrow">
		</a>
	</section>

  	<section id="about" class="container-fluid d-flex flex-wrap align-content-center ">
	    <div class="section-title mx-auto"> 
			ABOUT ME
  		</div>
	    <div class="row align-items-center justify-content-center">
			<div class="col-sm-5 mr-3">
				<img class="profpic" src="{% static 'images/profile.jpg' %}" alt="Profile Picture">
				<article class="text-justify">
					I’m a young girl who loves logical thinking and has a burning passion in Computer Science. I recently made the discovery that seeing children’s laughter induces the happiness in me too.
				</article>
			</div>
			
			<div class="col-sm-4 mr-3">
				<h4> FULL NAME </h4>
				<h5> Fairuza Raryasdya Ayunda </h5>
				<br>
				<h4> EDUCATION </h4>
				<h5> Faculty of Computer Science, </h5>
				<h5> University of Indonesia </h5>
				<br>
				<h4> CONTACT </h4>
				<h5> fairuza.raryasdya@ui.ac.id </h5>
			</div>
		</div>
	</section>

	<section id="education" class="container-fluid">
		<div class="section-title mx-auto text-center"> 
  			EDUCATION
  		</div>

		<div class="row justify-content-center mb-3">
			<div class="col-sm-4">
				<img class="pic" src="{% static 'images/Makara_UI.png' %}" alt="Universitas Indonesia">
			</div>
			<div class="col-sm-6">
				<h4> Universitas Indonesia <h4>
				<h5> 2019 - present </h5>
				<p> Public Relations Staff, Pemira Fasilkom UI 2019 </p>
				<p> Head of Public Relations Division, DPM Fasilkom UI 2020 </p>
			</div>
		</div>
			
		<div class="row justify-content-center mb-3">
			<div class="d-flex pic-box col-sm-4">
				<img class="pic" src="{% static 'images/sma.png' %}" alt="SMAN 2 Tangerang Selatan">
			</div>
			<div class="col-sm-6">
				<h4> SMAN 2 Tangerang Selatan </h4>
				<h5> 2016 - 2019 </h5>
				<p> Silver Medalist, National Science Olympiad in Informatics 2018 </p>
			</div>
		</div>
		
		<div class="row justify-content-center mb-3">
			<div class="col-sm-4">
				<img class="pic" src="{% static 'images/smp.png' %}" alt="SMP Islam Al-Azhar BSD" style="width: 200px;">
			</div>
			<div class="col-sm-6">
				<h4> SMP Islam Al-Azhar BSD </h4>
				<h5> 2013 - 2016 </h5>
				<p> Member of Student Council </p>
			</div>
		</div>
	</section>

	<section id="more" class="container-fluid">
		<div class="row">
			<div class="col-sm-6">
				<div class="row left-side">
					<div class="special col">
			  		  <div class="row mx-auto mb-4">
						<div class="col-sm-6 mt-4 mb-4">
							<img src="{% static 'images/footer-edit.jpg' %}" alt="Children" style="max-width: 100%;">
						</div>
						<div class="special d-flex col-sm-6 left-text">
			  				Observing children's joy fills up my happiness metre. Click to find out what we did together.
			  			</div>
			  		  </div>
					  <a href="{% url 'story_4:extra' %}" class="d-flex m-auto click">
		  				CLICK HERE
			  		  </a>
		  			</div>
		  		</div>
		  	</div>

		  	<div class="col-sm-6">
				<div class="row right-side">
					<div class="col">
						<div class="contact">
							CONTACT ME AT
						</div>

						<div class="row">
							<div class="col-sm-4">
							  <a href="mailto:fairuza.raryasdya@ui.ac.id">
								<span class="iconify" data-inline="false" data-icon="feather:mail" style="color: #F9E1E0; font-size: 75px;"></span>
							  </a>
							</div>
							<div class="col-sm-4">
							  <a href="https://instagram.com/fairuzafe" target="_blank">
								<span class="iconify" data-inline="false" data-icon="ant-design:instagram-outlined" style="color: #F9E1E0; font-size: 75px;"></span>
							  </a>
							</div>
							<div class="col-sm-4">
				  			  <a href="https://linkedin.com/in/raryasdya" target="_blank">
				  				<span class="iconify" data-inline="false" data-icon="jam:linkedin-square" style="color: #F9E1E0; font-size: 75px;"></span>
				  			  </a>
				  			</div>
				  		</div>
			  		</div>
		  		</div>
		  	</div>
  		</div>
  	</section>  	

{% endblock %}

story_4/templates/time.html
{% extends 'base.html' %}
{% load static %}
{% block title %} What time is it? {% endblock %}

{% block content %}
{% include 'navbar.html' %}
	<br>
	<br>
	<br>
	<p class="pl-5"> Current UTC time {{ utc_time | time:"H:i:s"}}</p>
	<p class="pl-5"> Current UTC + {{ utc }} time is {{ timezone_time | time:"H:i:s"}}</p>

{% endblock %}

story_5/templates/add_subject.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Subject{% endblock %}
{% block content %}

{% include 'navbar.html' %}

<section class="container-fluid d-flex flex-wrap align-content-center ">
{% if submitted %}
	<div class="success p-5 col-12 text-center">
		Your subject was submitted successfully. Thank you :)
	</div>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story_5:subject' %}" class="text-white">
			Back to Subject List
		</a>
	</button>
{% else %}
	<div class="section-title mx-auto text-center p-5"> 
		ADD SUBJECT
	</div>

	<form action="" method="post" novalidate>
		{% csrf_token %}
		<table class="table mx-5" style="width:90vw">
			{{ form.as_table }}
			<tr>
				<td>&nbsp;</td>
				<td><input type="submit" value="Submit" class="btn btn-primary click"></td>
			</tr>
		</table>
	</form>
{% endif %}

</section>

{% endblock content %}

story_5/templates/subject_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ subject.matkul }} {% endblock %}

{% block content %}
{% include 'navbar.html' %}
	<section class="container-fluid d-flex flex-wrap align-content-center ">
		<div class="section-title m-auto text-center"> 
			{{ subject.matkul }}
		</div>
  	  <table class="table table-bordered mx-5" style="width:90vw">
		<tbody>
			<tr>
				<td> <b> Lecturer </b> </td>
				<td> {{ subject.dosen }} </td>
			</tr>
			<tr>
				<td> <b> Credit(s) </b> </td>
				<td> {{ subject.sks }} </td>
			</tr>
			<tr>
				<td> <b> Term </b> </td>
				<td> {{ subject.semester }} </td>
			</tr>
			<tr>
				<td> <b> Classroom </b> </td>
				<td> {{ subject.kelas }} </td>
			</tr>
			<tr>
				<td> <b> Description </b> </td>
				<td> {{ subject.deskripsi }} </td>
			</tr>
		</tbody>
	  </table>

	  <table class="table table-bordered mx-5" style="width:90vw">
		  <tr> 
		  	<td> <b> Tasks </b> </td>
		  </tr>
		
		{% for x in overdue %}
		  <tr class="table-danger">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}

		{% for x in near %}
		  <tr class="table-warning">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}

		{% for x in far %}
		  <tr class="table-success">
			<td> {{ x.tugas }} </td>
			<td> {{ x.deadline }} </td>
		  </tr>
		{% endfor %}
	  </table>

	  <button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story_5:subject' %}" class="text-white">
			Back to Subject List
		</a>
	  </button>
  	</section>>

{% endblock %}

story_5/templates/subject_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Subject List {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container-fluid d-flex flex-wrap align-content-center ">
	<div class="section-title mx-auto text-center"> 
			SUBJECT LIST
	</div>
	<table class="table table-bordered mx-5" style="width:90vw">
	  <thead class="thead-light text-center">
	    <tr>
	      <th>Subject</th>
	      <th>Lecturer</th>
	      <th>Credit(s)</th>
	      <th>Delete</th>
	    </tr>
	  </thead>
		<tbody>
		    {% for x in subject_list %}
			<tr>
				<td> <a href="detail/{{ x.id }}">{{ x.matkul }} </a> </td>
				<td> {{ x.dosen }} </td>
				<td class="text-center"> {{ x.sks }} </td>
				<td class="text-center"> 
					<form method="POST" action="{% url 'story_5:subject' %}">
			          {% csrf_token %}
			          <input name="id" value="{{x.id}}" type="hidden">
			          <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2" style="font-size: 0.8rem;">Delete</button>
			        </form>
				</td>
			</tr>
		    {% endfor %}
		</tbody>
	</table>

	<button class="btn btn-primary d-flex m-auto click"> 
		<a href="{% url 'story_5:add_subject' %}" class="text-white">
			Add New Subject
		</a>
	</button>
</section>
{% endblock %}

story_6/templates/activity.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Activity {% endblock %}

{% block content %}
{% include 'navbar.html' %}
<section class="container-fluid d-flex flex-wrap align-content-center mt-5">
	<div class="section-title mx-auto text-center mt-5"> 
			ACTIVITY LIST
	  <a href="{% url 'story_6:add_activity' %}" class="text-white">
		<button class="btn btn-primary d-flex mx-auto my-2 click">
			Add New Activity
		</button>
	  </a>
	</div>

	<div class="row w-100 justify-content-center">
		{% for x in activity %}
			<div class="col-4 m-4 p-4 rounded border">
				<ul class="list-group">
				  <li class="list-group-item list-group-item-secondary"> <b> {{ x.kegiatan }} </b> </li>

			      {% for y in attendees %}
				    {% if y.kegiatan == x %}
					  	<form method="POST" action="{% url 'story_6:activity' %}">
					    {% csrf_token %}
					    <input name="id" value="{{y.id}}" type="hidden">
				  		<li class="list-group-item"> 
				  			<div class="d-flex justify-content-between"> 
				  				{{ y.nama }} 
					          <button type="submit" value="Submit" class="btn btn-primary" style="font-size: 0.8rem;"> 
					          x
					           </button>
					        </form>
				  			</div>
				  		</li>
				    {% endif %}
			      {% endfor %}
				</ul>

				<div class="section-title mx-auto text-center"> 
				  <a href="register/{{ x.id }}" class="text-white">
					<button class="btn btn-primary d-flex mx-auto my-2 click">
					  	Register Yourself
					</button>
				  </a>
				</div>
			</div>
		{% endfor %}
	</div>

</section>
{% endblock %}

templates/navbar.html
<div class="dropdown fixed-top">
  <button class="btn btn-secondary dropdown-toggle ml-4 pl-3 pr-3"
          type="button" id="dropdownMenu1" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
    Menu
  </button>
   <div class="dropdown-menu">
      <a class="dropdown-item" href="{% url 'story_4:home' %}#home">Home</a>
      <a class="dropdown-item" href="{% url 'story_4:home' %}#about">About Me</a>
      <a class="dropdown-item" href="{% url 'story_4:home' %}#education">Education</a>
      <a class="dropdown-item" href="{% url 'story_4:home' %}#more">More</a>
      
      <div class="dropdown-divider"></div>
      <h6 class="dropdown-header"> Story 5 </h6>
      <a class="dropdown-item" href="{% url 'story_5:subject' %}">Subject List</a>
      <a class="dropdown-item" href="{% url 'story_5:add_subject' %}">Add Subject</a>

      <div class="dropdown-divider"></div>
      <h6 class="dropdown-header"> Story 6 </h6>
      <a class="dropdown-item" href="{% url 'story_6:activity' %}"> Activity List </a>
      <a class="dropdown-item" href="{% url 'story_6:add_activity' %}"> Add Activity </a>

      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url 'story_1:home' %}" target="_blank">Story 1</a>
      <a class="dropdown-item" href="{% url 'story_4:time' %}">Time</a>
    </div>
</div>